services:
  - type: web
    name: programyx-au
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads-disk
      mountPath: /uploads
      sizeGB: 1
